export interface ISkillDictionaryEntry {
  keyword: string;
  skill: string;
  tool?: string;
}

export const SKILL_DICTIONARY: ISkillDictionaryEntry[] = [
  // Programming languages
  { keyword: "javascript", skill: "JavaScript" },
  { keyword: "typescript", skill: "TypeScript" },
  { keyword: "python", skill: "Python" },
  { keyword: "java", skill: "Java" },
  { keyword: "c++", skill: "C++" },
  { keyword: "c#", skill: "C#" },
  { keyword: "go", skill: "Go" },
  { keyword: "ruby", skill: "Ruby" },
  { keyword: "php", skill: "PHP" },
  { keyword: "swift", skill: "Swift" },
  { keyword: "kotlin", skill: "Kotlin" },
  { keyword: "rust", skill: "Rust" },
  { keyword: "html", skill: "HTML" },
  { keyword: "css", skill: "CSS" },
  { keyword: "sass", skill: "Sass" },
  { keyword: "sql", skill: "SQL" },
  { keyword: "nosql", skill: "NoSQL" },
  { keyword: "shell scripting", skill: "Shell Scripting" },
  // Frontend frameworks & libraries
  { keyword: "react", skill: "React" },
  { keyword: "next.js", skill: "Next.js" },
  { keyword: "nextjs", skill: "Next.js" },
  { keyword: "angular", skill: "Angular" },
  { keyword: "vue", skill: "Vue.js" },
  { keyword: "svelte", skill: "Svelte" },
  { keyword: "tailwind", skill: "Tailwind CSS" },
  { keyword: "bootstrap", skill: "Bootstrap" },
  { keyword: "jquery", skill: "jQuery" },
  { keyword: "redux", skill: "Redux" },
  { keyword: "zustand", skill: "Zustand" },
  { keyword: "webpack", skill: "Webpack" },
  // Backend frameworks
  { keyword: "node.js", skill: "Node.js" },
  { keyword: "nodejs", skill: "Node.js" },
  { keyword: "express", skill: "Express.js" },
  { keyword: "django", skill: "Django" },
  { keyword: "flask", skill: "Flask" },
  { keyword: "spring boot", skill: "Spring Boot" },
  { keyword: "springboot", skill: "Spring Boot" },
  { keyword: "rails", skill: "Ruby on Rails" },
  { keyword: "laravel", skill: "Laravel" },
  { keyword: ".net", skill: ".NET" },
  { keyword: "fastapi", skill: "FastAPI" },
  // Databases
  { keyword: "mongodb", skill: "MongoDB" },
  { keyword: "postgresql", skill: "PostgreSQL" },
  { keyword: "mysql", skill: "MySQL" },
  { keyword: "redis", skill: "Redis" },
  { keyword: "firebase", skill: "Firebase" },
  { keyword: "supabase", skill: "Supabase" },
  { keyword: "mongoose", skill: "Mongoose" },
  { keyword: "prisma", skill: "Prisma" },
  // DevOps & cloud
  { keyword: "git", skill: "Git" },
  { keyword: "github", skill: "GitHub" },
  { keyword: "gitlab", skill: "GitLab" },
  { keyword: "docker", skill: "Docker" },
  { keyword: "kubernetes", skill: "Kubernetes" },
  { keyword: "aws", skill: "AWS" },
  { keyword: "azure", skill: "Microsoft Azure" },
  { keyword: "gcp", skill: "Google Cloud" },
  { keyword: "google cloud", skill: "Google Cloud" },
  { keyword: "cicd", skill: "CI/CD" },
  { keyword: "jenkins", skill: "Jenkins" },
  { keyword: "linux", skill: "Linux" },
  { keyword: "rest api", skill: "REST APIs" },
  { keyword: "graphql", skill: "GraphQL" },
  // Data & ML
  { keyword: "machine learning", skill: "Machine Learning" },
  { keyword: "deep learning", skill: "Deep Learning" },
  { keyword: "tensorflow", skill: "TensorFlow" },
  { keyword: "pytorch", skill: "PyTorch" },
  { keyword: "scikit-learn", skill: "scikit-learn" },
  { keyword: "scikit learn", skill: "scikit-learn" },
  { keyword: "pandas", skill: "Pandas" },
  { keyword: "numpy", skill: "NumPy" },
  { keyword: "data analysis", skill: "Data Analysis" },
  { keyword: "data analytics", skill: "Data Analytics" },
  { keyword: "data visualization", skill: "Data Visualization" },
  { keyword: "tableau", skill: "Tableau" },
  { keyword: "power bi", skill: "Power BI" },
  { keyword: "excel", skill: "Excel" },
  { keyword: "statistics", skill: "Statistics" },
  { keyword: "nlp", skill: "Natural Language Processing" },
  // Design
  { keyword: "figma", skill: "Figma" },
  { keyword: "adobe xd", skill: "Adobe XD" },
  { keyword: "photoshop", skill: "Photoshop" },
  { keyword: "illustrator", skill: "Illustrator" },
  { keyword: "ui/ux", skill: "UI/UX Design" },
  { keyword: "ui design", skill: "UI Design" },
  { keyword: "ux design", skill: "UX Design" },
  { keyword: "ux research", skill: "UX Research" },
  { keyword: "wireframing", skill: "Wireframing" },
  { keyword: "prototyping", skill: "Prototyping" },
  { keyword: "design systems", skill: "Design Systems" },
  { keyword: "graphic design", skill: "Graphic Design" },
  { keyword: "sketch", skill: "Sketch" },
  // Marketing
  { keyword: "seo", skill: "SEO" },
  { keyword: "sem", skill: "SEM" },
  { keyword: "google analytics", skill: "Google Analytics" },
  { keyword: "content marketing", skill: "Content Marketing" },
  { keyword: "social media marketing", skill: "Social Media Marketing" },
  { keyword: "email marketing", skill: "Email Marketing" },
  { keyword: "copywriting", skill: "Copywriting" },
  { keyword: "digital marketing", skill: "Digital Marketing" },
  { keyword: "facebook ads", skill: "Facebook Ads" },
  { keyword: "google ads", skill: "Google Ads" },
  { keyword: "marketing automation", skill: "Marketing Automation" },
  { keyword: "branding", skill: "Branding" },
  { keyword: "market research", skill: "Market Research" },
  // Tools
  { keyword: "jira", skill: "Jira", tool: "Jira" },
  { keyword: "slack", skill: "Slack", tool: "Slack" },
  { keyword: "notion", skill: "Notion", tool: "Notion" },
  { keyword: "postman", skill: "Postman", tool: "Postman" },
  { keyword: "vs code", skill: "VS Code", tool: "VS Code" },
  { keyword: "webflow", skill: "Webflow", tool: "Webflow" },
  { keyword: "wordpress", skill: "WordPress", tool: "WordPress" },
  { keyword: "shopify", skill: "Shopify", tool: "Shopify" },
  // Soft skills
  { keyword: "communication", skill: "Communication" },
  { keyword: "teamwork", skill: "Teamwork" },
  { keyword: "leadership", skill: "Leadership" },
  { keyword: "problem solving", skill: "Problem Solving" },
  { keyword: "time management", skill: "Time Management" },
  { keyword: "critical thinking", skill: "Critical Thinking" },
  { keyword: "adaptability", skill: "Adaptability" },
];

export const ROLE_DICTIONARY: { keyword: string; role: string; track: string }[] = [
  { keyword: "frontend", role: "Frontend Developer", track: "Web Development" },
  { keyword: "front-end", role: "Frontend Developer", track: "Web Development" },
  { keyword: "backend", role: "Backend Developer", track: "Web Development" },
  { keyword: "back-end", role: "Backend Developer", track: "Web Development" },
  { keyword: "full stack", role: "Full Stack Developer", track: "Web Development" },
  { keyword: "fullstack", role: "Full Stack Developer", track: "Web Development" },
  { keyword: "web developer", role: "Web Developer", track: "Web Development" },
  { keyword: "software engineer", role: "Software Engineer", track: "Web Development" },
  { keyword: "app developer", role: "App Developer", track: "Web Development" },
  { keyword: "mobile developer", role: "Mobile Developer", track: "Web Development" },
  { keyword: "devops engineer", role: "DevOps Engineer", track: "Web Development" },
  { keyword: "data scientist", role: "Data Scientist", track: "Data" },
  { keyword: "data analyst", role: "Data Analyst", track: "Data" },
  { keyword: "data engineer", role: "Data Engineer", track: "Data" },
  { keyword: "business analyst", role: "Business Analyst", track: "Data" },
  { keyword: "machine learning engineer", role: "Machine Learning Engineer", track: "Data" },
  { keyword: "ml engineer", role: "Machine Learning Engineer", track: "Data" },
  { keyword: "ui/ux designer", role: "UI/UX Designer", track: "Design" },
  { keyword: "ui designer", role: "UI Designer", track: "Design" },
  { keyword: "ux designer", role: "UX Designer", track: "Design" },
  { keyword: "graphic designer", role: "Graphic Designer", track: "Design" },
  { keyword: "product designer", role: "Product Designer", track: "Design" },
  { keyword: "visual designer", role: "Visual Designer", track: "Design" },
  { keyword: "digital marketer", role: "Digital Marketer", track: "Marketing" },
  { keyword: "content writer", role: "Content Writer", track: "Marketing" },
  { keyword: "seo specialist", role: "SEO Specialist", track: "Marketing" },
  { keyword: "social media manager", role: "Social Media Manager", track: "Marketing" },
  { keyword: "marketing manager", role: "Marketing Manager", track: "Marketing" },
  { keyword: "community manager", role: "Community Manager", track: "Marketing" },
];