import { JobOpportunity } from "../src/app/modules/jobOpportunity/jobOpportunity.model.js";
const jobs = [
    {
        title: "Frontend Developer",
        company: "Smart Soult Bangladesh",
        location: "Dhaka",
        requiredSkills: ["React", "TypeScript", "Tailwind CSS", "HTML", "CSS"],
        experienceLevel: "Junior",
        type: "Full-time",
        track: "Web Development",
        description: "We are looking for a passionate Frontend Developer to join our growing team. You will work on building responsive web applications using modern JavaScript frameworks. Responsibilities include implementing UI components, collaborating with designers, and ensuring cross-browser compatibility.",
        externalLinks: {
            linkedin: "https://linkedin.com/jobs/view/frontend-developer-smart-soult",
            bdjobs: "https://bdjobs.com/job/frontend-developer",
        },
    },
    {
        title: "React.js Intern",
        company: "Codevative Ltd.",
        location: "Chittagong",
        requiredSkills: ["React", "JavaScript", "HTML", "CSS"],
        experienceLevel: "Fresher",
        type: "Internship",
        track: "Web Development",
        description: "Join our internship program to gain hands-on experience with React.js. You will work alongside senior developers on real client projects, learn best practices in component architecture, and contribute to our internal tools. Ideal for recent graduates eager to start their career in web development.",
        externalLinks: {
            bdjobs: "https://bdjobs.com/job/react-intern-codevative",
        },
    },
    {
        title: "Full Stack Developer",
        company: "NextGen Solutions",
        location: "Remote",
        requiredSkills: ["React", "Node.js", "MongoDB", "Express", "TypeScript"],
        experienceLevel: "Junior",
        type: "Full-time",
        track: "Web Development",
        description: "We are seeking a Full Stack Developer comfortable working across the entire MERN stack. You will design and implement RESTful APIs, build React frontends, and manage MongoDB databases. Experience with Git, CI/CD, and agile workflows is a plus.",
        externalLinks: {
            linkedin: "https://linkedin.com/jobs/view/fullstack-nextgen",
        },
    },
    {
        title: "WordPress Developer",
        company: "PixelCraft Studio",
        location: "Dhaka",
        requiredSkills: ["WordPress", "PHP", "HTML", "CSS", "JavaScript"],
        experienceLevel: "Fresher",
        type: "Freelance",
        track: "Web Development",
        description: "Looking for a WordPress developer to build and customize client websites. You will work with page builders, custom themes, and plugins. Strong HTML/CSS skills and an eye for design are essential. Flexible hours, project-based work.",
        externalLinks: {},
    },
    {
        title: "Android Developer",
        company: "Appify Technologies",
        location: "Dhaka",
        requiredSkills: ["Kotlin", "Android SDK", "Jetpack Compose", "REST APIs"],
        experienceLevel: "Junior",
        type: "Full-time",
        track: "App Development",
        description: "We need an Android Developer to build and maintain mobile applications for our clients. You will work with Kotlin and Jetpack Compose, integrate REST APIs, and optimize app performance. Experience publishing apps on the Play Store is preferred.",
        externalLinks: {
            linkedin: "https://linkedin.com/jobs/view/android-dev-appify",
        },
    },
    {
        title: "Flutter Developer",
        company: "Dhaka Digital",
        location: "Dhaka",
        requiredSkills: ["Flutter", "Dart", "Firebase", "REST APIs"],
        experienceLevel: "Fresher",
        type: "Internship",
        track: "App Development",
        description: "Join our mobile team as a Flutter Developer intern. You will learn cross-platform mobile development, build UI components with Flutter widgets, and integrate backend services. Perfect for developers interested in building beautiful, performant mobile apps.",
        externalLinks: {
            bdjobs: "https://bdjobs.com/job/flutter-intern-dhaka-digital",
        },
    },
    {
        title: "React Native Developer",
        company: "Mobisoft Bangladesh",
        location: "Chittagong",
        requiredSkills: ["React Native", "JavaScript", "TypeScript", "Redux"],
        experienceLevel: "Junior",
        type: "Full-time",
        track: "App Development",
        description: "We are hiring a React Native Developer to build cross-platform mobile applications. You will implement native modules, manage state with Redux, and work closely with the design team to deliver pixel-perfect UIs on both iOS and Android.",
        externalLinks: {},
    },
    {
        title: "Unity Game Developer",
        company: "GameAxis Studios",
        location: "Remote",
        requiredSkills: ["Unity", "C#", "Game Design", "3D Modeling Basics"],
        experienceLevel: "Junior",
        type: "Full-time",
        track: "Game Development",
        description: "GameAxis Studios is looking for a Unity Game Developer to work on mobile and PC games. You will implement gameplay mechanics, optimize performance, and collaborate with artists and designers. A portfolio of shipped games or game jam projects is highly valued.",
        externalLinks: {
            linkedin: "https://linkedin.com/jobs/view/unity-dev-gameaxis",
        },
    },
    {
        title: "Game Design Intern",
        company: "Pixel Playground BD",
        location: "Dhaka",
        requiredSkills: ["Game Design", "Unity", "Prototyping", "Level Design"],
        experienceLevel: "Fresher",
        type: "Internship",
        track: "Game Development",
        description: "An exciting opportunity for aspiring game designers. You will assist in designing game mechanics, creating prototypes in Unity, and play-testing builds. Great for creative minds who want to break into the gaming industry.",
        externalLinks: {},
    },
    {
        title: "Backend Developer",
        company: "Infolytica Bangladesh",
        location: "Sylhet",
        requiredSkills: ["Node.js", "Express", "MongoDB", "TypeScript", "REST APIs"],
        experienceLevel: "Junior",
        type: "Full-time",
        track: "Software Engineering",
        description: "We need a Backend Developer to design and maintain scalable server-side applications. You will build RESTful APIs, manage database schemas, implement authentication systems, and ensure API security. Strong problem-solving skills required.",
        externalLinks: {
            linkedin: "https://linkedin.com/jobs/view/backend-infolytica",
        },
    },
    {
        title: "Software Engineer",
        company: "Bdasoft Inc.",
        location: "Dhaka",
        requiredSkills: ["JavaScript", "TypeScript", "Node.js", "React", "Git"],
        experienceLevel: "Junior",
        type: "Full-time",
        track: "Software Engineering",
        description: "Join our engineering team to build enterprise-grade web applications. You will work across the stack using TypeScript, contribute to architecture decisions, write unit tests, and participate in code reviews. We value clean code and continuous learning.",
        externalLinks: {
            bdjobs: "https://bdjobs.com/job/software-engineer-bdasoft",
        },
    },
    {
        title: "DevOps Intern",
        company: "CloudFirst Technologies",
        location: "Remote",
        requiredSkills: ["Docker", "Linux", "AWS Basics", "CI/CD", "Git"],
        experienceLevel: "Fresher",
        type: "Part-time",
        track: "Software Engineering",
        description: "Learn DevOps practices by working alongside our infrastructure team. You will assist with Docker containerization, CI/CD pipeline setup, cloud resource monitoring, and documentation. Ideal for CS students interested in cloud and infrastructure.",
        externalLinks: {},
    },
    {
        title: "Machine Learning Engineer",
        company: "DataPulse AI",
        location: "Remote",
        requiredSkills: ["Python", "TensorFlow", "PyTorch", "Scikit-learn", "NumPy"],
        experienceLevel: "Junior",
        type: "Full-time",
        track: "Machine Learning",
        description: "We are building AI-powered products for the Bangladeshi market. Join us as an ML Engineer to develop, train, and deploy machine learning models. You will work with large datasets, experiment with architectures, and collaborate with the product team to ship intelligent features.",
        externalLinks: {
            linkedin: "https://linkedin.com/jobs/view/ml-engineer-datapulse",
        },
    },
    {
        title: "AI Research Intern",
        company: "BUET AI Lab",
        location: "Dhaka",
        requiredSkills: ["Python", "Deep Learning", "Research", "TensorFlow"],
        experienceLevel: "Fresher",
        type: "Internship",
        track: "Machine Learning",
        description: "A research-focused internship at BUET's AI Lab. You will assist ongoing research projects in natural language processing and computer vision, implement research papers, and contribute to publications. Strong mathematical foundations preferred.",
        externalLinks: {},
    },
    {
        title: "Data Analyst",
        company: "Grameenphone Analytics",
        location: "Dhaka",
        requiredSkills: ["Python", "SQL", "Excel", "Pandas", "Data Visualization"],
        experienceLevel: "Fresher",
        type: "Full-time",
        track: "Data Science",
        description: "We need a Data Analyst to turn raw data into actionable insights. You will clean and analyze datasets, build dashboards, create reports, and present findings to stakeholders. Proficiency in SQL, Python (Pandas), and Excel is essential.",
        externalLinks: {
            linkedin: "https://linkedin.com/jobs/view/data-analyst-gp",
            bdjobs: "https://bdjobs.com/job/data-analyst-grameenphone",
        },
    },
    {
        title: "Junior Data Scientist",
        company: "Joules to Watts",
        location: "Dhaka",
        requiredSkills: ["Python", "Machine Learning", "SQL", "Pandas", "Statistics"],
        experienceLevel: "Fresher",
        type: "Full-time",
        track: "Data Science",
        description: "Join our data science team to build predictive models and analytics solutions. You will work with structured and unstructured data, develop ML pipelines, and collaborate with engineers to deploy models. A strong foundation in statistics and programming is required.",
        externalLinks: {
            linkedin: "https://linkedin.com/jobs/view/jr-datascientist-j2w",
        },
    },
    {
        title: "Business Intelligence Analyst",
        company: "Robi Axiata Limited",
        location: "Chittagong",
        requiredSkills: ["SQL", "Power BI", "Excel", "Data Analysis", "ETL"],
        experienceLevel: "Fresher",
        type: "Part-time",
        track: "Data Science",
        description: "Assist the BI team in building reports and dashboards using Power BI and SQL. You will extract data from multiple sources, transform it for analysis, and create visualizations that drive business decisions. Part-time role with flexible hours.",
        externalLinks: {
            bdjobs: "https://bdjobs.com/job/bi-analyst-robi",
        },
    },
    {
        title: "UI/UX Designer",
        company: "ByteForge Digital",
        location: "Dhaka",
        requiredSkills: ["Figma", "UI Design", "Prototyping", "User Research", "Wireframing"],
        experienceLevel: "Junior",
        type: "Full-time",
        track: "UI UX Design",
        description: "We are looking for a talented UI/UX Designer to create intuitive and beautiful digital experiences. You will conduct user research, create wireframes and prototypes in Figma, and work closely with developers to ensure design fidelity. A strong portfolio is required.",
        externalLinks: {
            linkedin: "https://linkedin.com/jobs/view/uiux-byteforge",
        },
    },
    {
        title: "Freelance Graphic & UI Designer",
        company: "Creative Nomad Studio",
        location: "Remote",
        requiredSkills: ["Figma", "Adobe XD", "Photoshop", "Illustrator", "UI Design"],
        experienceLevel: "Junior",
        type: "Freelance",
        track: "UI UX Design",
        description: "Work with international clients on UI/UX design projects. You will design landing pages, mobile app interfaces, and brand assets. Must have a strong portfolio and be comfortable communicating with clients in English. Remote, flexible schedule.",
        externalLinks: {},
    },
    {
        title: "Digital Marketing Specialist",
        company: "品牌 BrandBD",
        location: "Dhaka",
        requiredSkills: ["SEO", "Google Ads", "Social Media Marketing", "Analytics", "Content Strategy"],
        experienceLevel: "Fresher",
        type: "Full-time",
        track: "Marketing",
        description: "We need a Digital Marketing Specialist to grow our online presence and drive lead generation. You will manage SEO campaigns, run Google and Facebook ads, create content strategies, and analyze campaign performance using Google Analytics.",
        externalLinks: {
            bdjobs: "https://bdjobs.com/job/digital-marketing-brandbd",
        },
    },
    {
        title: "Social Media & Content Executive",
        company: "ShopUp (a Bkash venture)",
        location: "Dhaka",
        requiredSkills: ["Content Writing", "Social Media Management", "Copywriting", "Canva", "Analytics"],
        experienceLevel: "Fresher",
        type: "Part-time",
        track: "Marketing",
        description: "Manage social media accounts and create engaging content for our e-commerce platform. You will write copy, design graphics in Canva, schedule posts, and track engagement metrics. A creative mind with excellent English and Bangla writing skills.",
        externalLinks: {
            linkedin: "https://linkedin.com/jobs/view/content-exec-shopup",
        },
    },
];
export const seedJobs = async () => {
    await JobOpportunity.deleteMany({});
    const result = await JobOpportunity.insertMany(jobs);
    return result.length;
};
//# sourceMappingURL=seedJobs.js.map